language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd misc/test-scenario
- export BUNDLE_GEMFILE=$PWD/Gemfile
- bundle install
- RAILS_ENV=test bundle exec rake db:migrate
- rvmsudo rails s -d -e test -p 80
- sleep 3
- cd ../..
- export BUNDLE_GEMFILE=$PWD/Gemfile
script: make test
after_script:
- sudo kill `cat misc/test-scenario/tmp/pids/server.pid`
addons:
  sauce_connect: true
env:
  global:
  - secure: kou5wVnENwnwQFaiepw86q5x3wur2Dxi52+CsipWfzTFiq7FzYFm/xExLCL8GDHVpfza/OtCX3bL1JSkFmFLJ9hRGjGBCh81OAsTsns2LxgyZ1832hvck8P4ikcpjkhaQm5nQFNKlPqafaKT0Hti4/UZhA/3BeQAeR2lOmf9meI=
  - secure: BK7W2x/qbqeFXodw+T5twbmq5V3RJbcF1ACn/T8jm0ElGFkkWy+ugdekMhiWXl+CB857l9kfOiG/1JDF/0vJMxlAObhJjgspdZIQACRqLMhhKmIhKUHLBxOI974QDjxifU8YPZe9Lla0IErWs8yLBt9E1q3c8Nq0hrf9Hp85A24=
  - secure: aguTWKUZBkE+u1LMBr9LIWkQeugaBH6fGsfTwbOlQGy5LqYbeJH/IFeobV/7JxPJVgZdN8wRpq1rj9UPEkRz1UlDpzeqiTs4zIM2O8wDqsC+tq804FAvjWE8qi4ud1eWdPYY+ItLkQSA39ofDCSvIi8ESG5EZeBrg8W5Pf6WRSU=
